services:
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - mysql8
    tty: true
    stdin_open: true
  mysql8:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql8-volume:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysql8-volume:
